import numpy as np

peptides = {'A':'alanyl', 'C':'cysteinyl', 'D':'aspartyl', 'E':'glutamyl', 'F':'phenylalanyl', 
            'G':'glycyl', 'H':'histidyl', 'I':'isoleucyl', 'K':'lysyl', 'L':'leucyl', 
            'M':'methionyl', 'N':'asparaginyl', 'P':'prolyl', 'Q':'glutaminyl', 'R':'arginyl', 
            'S':'seryl', 'T':'threonyl', 'V':'valyl', 'W':'tryptophyl', 'Y':'tyrosyl'}

acyls = {'Ala':'alanyl', 'Cys':'cysteinyl', 'Asp':'aspartyl', 'Glu':'glutamyl', 'Phe':'phenylalanyl', 
         'Gly':'glycyl', 'His':'histidyl', 'Ile':'isoleucyl', 'Lys':'lysyl', 'Leu':'leucyl', 
         'Met':'methionyl', 'Asn':'asparaginyl', 'Pro':'prolyl', 'Gln':'glutaminyl', 'Arg':'arginyl', 
         'Ser':'seryl', 'Thr':'threonyl', 'Val':'valyl', 'Trp':'tryptophyl', 'Tyr':'tyrosyl'}
             
# 1967 sequence
sequence = 'Met-Gln-Arg-Tyr-Glu-Ser-Leu-Phe-Ala-Gln-Leu-Lys-Glu-Arg-Lys-Glu-Gly-Ala-Phe-Val-Pro-Phe-Val-Thr-Leu-Gly-Asp-Pro-Gly-Ile-Glu-Gln-Ser-Leu-Lys-Ile-Asp-Thr-Leu-Ile-Glu-Ala-Gly-Ala-Asp-Ala-Leu-Glu-Leu-Gly-Ile-Pro-Phe-Ser-Asp-Pro-Leu-Ala-Asp-Gly-Pro-Thr-Ile-Gln-Asn-Ala-Thr-Leu-Arg-Ala-Phe-Ala-Ala-Gly-Val-Thr-Pro-Ala-Gln-Cys-Phe-Glu-Met-Leu-Ala-Leu-Ile-Arg-Gln-Lys-His-Pro-Thr-Ile-Pro-Ile-Gly-Leu-Leu-Met-Tyr-Ala-Asn-Leu-Val-Phe-Asn-Lys-Gly-Ile-Asp-Glu-Phe-Tyr-Ala-Gln-Cys-Glu-Lys-Val-Gly-Val-Asp-Ser-Val-Leu-Val-Ala-Asp-Val-Pro-Val-Gln-Glu-Ser-Ala-Pro-Phe-Arg-Gln-Ala-Ala-Leu-Arg-His-Asn-Val-Ala-Pro-Ile-Phe-Ile-Cys-Pro-Pro-Asn-Ala-Asp-Asp-Asp-Leu-Leu-Arg-Gln-Ile-Ala-Ser-Tyr-Gly-Arg-Gly-Tyr-Thr-Tyr-Leu-Leu-Ser-Arg-Ala-Gly-Val-Thr-Gly-Ala-Glu-Asn-Arg-Ala-Ala-Leu-Pro-Leu-Asn-His-Leu-Val-Ala-Lys-Leu-Lys-Glu-Tyr-Asn-Ala-Ala-Pro-Pro-Leu-Gln-Gly-Phe-Gly-Ile-Ser-Ala-Pro-Asp-Gln-Val-Lys-Ala-Ala-Ile-Asp-Ala-Gly-Ala-Ala-Gly-Ala-Ile-Ser-Gly-Ser-Ala-Ile-Val-Lys-Ile-Ile-Glu-Gln-His-Asn-Ile-Glu-Pro-Glu-Lys-Met-Leu-Ala-Ala-Leu-Lys-Val-Phe-Val-Gln-Pro-Met-Lys-Ala-Ala-Thr-Arg-Ser'
# Modern sequence (strain K12)
shortseq = 'MERYESLFAQLKERKEGAFVPFVTLGDPGIEQSLKIIDTLIEAGADALELGIPFSDPLADGPTIQNATLRAFAAGVTPAQCFEMLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAQCEKVGVDSVLVADVPVEESAPFRQAALRHNVAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQVKAAIDAGAAGAISGSAIVKIIEQHINEPEKMLAALKVFVQPMKAATRS'
'''
Amino acid sequences from variant strains of E. coli
O157:H7:           MERYESLFAQLKERKEGAFVPFVTLGDPGIEQSLKIIDTLIEAGADTLELGIPFSDPLADGPTIQNATLRAFAAGVTPAQCFEMLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAQCEKVGVDSVLVADVPVEESAPFRQAALRHNVAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQVKAAIDAGAAGAISGSAIVKIIEQHINEPKKMLAALKAFVQPMKAATRS
SE11:              MERYESLFAQLKERKEGAFVPFVTLGDPGIEQSLKIIDTLIEAGADALELGIPFSDPLADGPTIQNATLRAFAAGVTPAQCFEMLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAQCEKVGVDSVLVADVPIEESAPFRQAALRHNVAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQVKAAIDAGAAGAISGSAIVKIIEQHINEPEKMLAALKVFVQPMKAATRS
K12/DH10B:         MERYESLFAQLKERKEGAFVPFVTLGDPGIEQSLKIIDTLIEAGADALELGIPFSDPLADGPTIQNATLRAFAAGVTPAQCFEMLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAQCEKVGVDSVLVADVPVEESAPFRQAALRHNVAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQVKAAIDAGAAGAISGSAIVKIIEQHINEPEKMLAALKVFVQPMKAATRS
IAI1:              MERYESLFAQLKERKEGAFVPFVTLGDPGIEQSLKIIDTLIEAGADALELGIPFSDPLADGPTIQNATLRAFAAGVTPAQCFEMLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAQCEKVGVDSVLVADVPIEESAPFRQAALRHNVAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQVKAAIDAGAAGAISGSAIVKIIEQHINEPEKMLAALKVFVQPMKAATRS
ED1a:              MERYESLFTQLKERKEGAFIPFVTLGDPGIEQSLKIIDTLIEAGADALELGIPFSDPLADGPTIQNATLRAFAAGVTPAQCFEVLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAECEKVGVDSVLVADVPVEESAPFRQAALRHNVAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQVKAAIDAGAAGAISGSAIVKIIEQHINEPEKMLAALKAFVQPMKAATRS
UTI89/UPEC:        MERYESLFTQLKERKEGAFVPFVTLGDPGIEQSLKIIDTLIEAGADALELGIPFSDPLADGPTIQNATLRAFAAGVTPAQCFEVLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAECEKVGVDSVLVADVPVEESAPFRQAALRHNVAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQVKAAIDAGAAGAISGSAIVKIIEQHINEPEKMLAALKAFVQPMKAATRS
K12/MC4100/BW2952: MERYESLFAQLKERKEGAFVPFVTLGDPGIEQSLKIIDTLIEAGADALELGIPFSDPLADGPTIQNATLRAFAAGVTPAQCFEMLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAQCEKVGVDSVLVADVPVEESAPFRQAALRHNVAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQVKAAIDAGAAGAISGSAIVKIIEQHINEPEKMLAALKVFVQPMKAATRS
E24377A/ETEC:      MERYESLFAQLKERKEGAFVPFVTLGDPGIEQSLKIIDTLIEAGADALELGIPFSDPLADGPTIQNATLRAFAAGVTPAQCFEMLALIRQKHPTIPIGLLMYANLVFNKGIDEFYAQCEKVGVDSVLVADVPIEESAPFRQAALRHNVAPIFICPPNADDDLLRQIASYGRGYTYLLSRAGVTGAENRAALPLNHLVAKLKEYNAAPPLQGFGISAPDQVKAPIDAGAAGAISGSAIVKIIEQHINEPEKMLAALKVFVQPMKAATRS
'''
name = ''
name2 = ''
count = 0
for i in range(0,267):
    if i<266:
        code1 = sequence[i*4:i*4+3]
        name = name + acyls[code1]
    code2 = shortseq[i]
    name2 = name2 + peptides[code2]
    count += len(peptides[code2])
name = name + 'serine'
name2 = name2 + 'serine'
#print(name)
#print(len(name))
print(name2)
print(len(name2),' amino acids')